import { describe, expect, it } from 'vitest';

import {
  applyCodeSigningConfig,
  CODE_SIGNING_CONFIG_LOGICAL_ID,
  isFrameworkCustomResource,
  type CfnResource,
} from '../src/cloudformation';

const build = (): Record<string, CfnResource> => ({
  MyFunctionLambdaFunction: {
    Type: 'AWS::Lambda::Function',
    Properties: { FunctionName: 'svc-myFunction' },
  },
  OtherFunctionLambdaFunction: {
    Type: 'AWS::Lambda::Function',
    Properties: { FunctionName: 'svc-otherFunction' },
  },
  ImageFunctionLambdaFunction: {
    Type: 'AWS::Lambda::Function',
    Properties: { FunctionName: 'svc-imageFunction', PackageType: 'Image' },
  },
  // A Lambda some other plugin injected: no artifact we can find, let alone sign.
  ForeignPluginLambda: {
    Type: 'AWS::Lambda::Function',
    Properties: {
      FunctionName: 'svc-some-other-plugin-warmer',
      Code: { S3Bucket: 'deploy', S3Key: 'serverless/svc/dev/1234-abc/warmer.zip' },
    },
  },
  // The framework's own custom-resource Lambda, as generated by an
  // `existing: true` S3 event. Shares one artifact with every other custom
  // resource in the service.
  CustomDashresourceDashexistingDashs3LambdaFunction: {
    Type: 'AWS::Lambda::Function',
    Properties: {
      FunctionName: 'svc-dev-custom-resource-existing-s3',
      Code: { S3Bucket: 'deploy', S3Key: 'serverless/svc/dev/1234-abc/custom-resources.zip' },
    },
  },
  SomeQueue: { Type: 'AWS::SQS::Queue', Properties: {} },
});

const options = {
  profileVersionArn: 'arn:aws:signer:us-east-1:1234:/signing-profiles/my-profile/ABC',
  signingPolicy: 'Enforce' as const,
  serviceName: 'svc',
  userFunctionNames: new Set(['svc-myFunction', 'svc-otherFunction', 'svc-imageFunction']),
  includeCustomResources: true,
};

describe('applyCodeSigningConfig', () => {
  it('adds exactly one code signing config', () => {
    const resources = build();
    applyCodeSigningConfig(resources, options);

    const configs = Object.values(resources).filter(
      (resource) => resource.Type === 'AWS::Lambda::CodeSigningConfig'
    );
    // One per function, all wired to the last one, would leave the rest
    // orphaned in the template.
    expect(configs).toHaveLength(1);
    expect(resources[CODE_SIGNING_CONFIG_LOGICAL_ID]?.Properties).toMatchObject({
      AllowedPublishers: { SigningProfileVersionArns: [options.profileVersionArn] },
      CodeSigningPolicies: { UntrustedArtifactOnDeployment: 'Enforce' },
    });
  });

  it('attaches the config to user zip functions only', () => {
    const resources = build();
    applyCodeSigningConfig(resources, options);

    const ref = { Ref: CODE_SIGNING_CONFIG_LOGICAL_ID };
    expect(resources.MyFunctionLambdaFunction?.Properties?.CodeSigningConfigArn).toEqual(ref);
    expect(resources.OtherFunctionLambdaFunction?.Properties?.CodeSigningConfigArn).toEqual(ref);
  });

  it('skips container-image functions, which cannot carry the arn', () => {
    const resources = build();
    applyCodeSigningConfig(resources, options);
    expect(resources.ImageFunctionLambdaFunction?.Properties?.CodeSigningConfigArn).toBeUndefined();
  });

  it('skips lambdas serverless generated that are not user functions', () => {
    const resources = build();
    applyCodeSigningConfig(resources, options);
    expect(resources.CustomInternalLambda?.Properties?.CodeSigningConfigArn).toBeUndefined();
  });
});

/**
 * Events declared with `existing: true`, plus EventBridge, Cognito user pools
 * and the API Gateway CloudWatch role, make Serverless inject its own Lambdas
 * at `package:compileEvents`. They are not in `serverless.yml`, but they run
 * code in the account with permission to reconfigure buckets and event sources.
 */
describe('framework custom-resource functions', () => {
  const s3Key = 'serverless/svc/dev/1234-abc/custom-resources.zip';

  it('recognises them by artifact, not by logical ID', () => {
    expect(
      isFrameworkCustomResource({
        Type: 'AWS::Lambda::Function',
        Properties: { Code: { S3Bucket: 'deploy', S3Key: s3Key } },
      })
    ).toBe(true);

    expect(
      isFrameworkCustomResource({
        Type: 'AWS::Lambda::Function',
        Properties: { Code: { S3Bucket: 'deploy', S3Key: 'serverless/svc/dev/1/warmer.zip' } },
      })
    ).toBe(false);

    // A function whose name merely looks like a custom resource is not one.
    expect(
      isFrameworkCustomResource({
        Type: 'AWS::Lambda::Function',
        Properties: { FunctionName: 'svc-custom-resources.zip' },
      })
    ).toBe(false);
  });

  it('signs them by default', () => {
    const resources = build();
    const result = applyCodeSigningConfig(resources, options);

    expect(
      resources.CustomDashresourceDashexistingDashs3LambdaFunction?.Properties
        ?.CodeSigningConfigArn
    ).toEqual({ Ref: CODE_SIGNING_CONFIG_LOGICAL_ID });
    expect(result.customResourceFunctions).toBe(1);
    expect(result.skippedCustomResourceFunctions).toEqual([]);
  });

  it('names them when they are deliberately opted out', () => {
    const resources = build();
    const result = applyCodeSigningConfig(resources, {
      ...options,
      includeCustomResources: false,
    });

    expect(
      resources.CustomDashresourceDashexistingDashs3LambdaFunction?.Properties
    ).not.toHaveProperty('CodeSigningConfigArn');
    expect(result.customResourceFunctions).toBe(0);
    expect(result.skippedCustomResourceFunctions).toEqual([
      'svc-dev-custom-resource-existing-s3',
    ]);
  });

  it('still leaves other plugins\' Lambdas alone either way', () => {
    const resources = build();
    applyCodeSigningConfig(resources, { ...options, includeCustomResources: true });

    // We cannot find its artifact, so we cannot sign it, so attaching an
    // Enforce policy to it would only break the deploy.
    expect(resources.ForeignPluginLambda?.Properties).not.toHaveProperty('CodeSigningConfigArn');
  });
});

/**
 * "Is every function in this stack signed?" has to be answerable from the
 * result, so every AWS::Lambda::Function lands in exactly one bucket and the
 * ones that are not covered are named rather than dropped.
 */
describe('coverage accounting', () => {
  it('names what it could not sign, and why', () => {
    const resources = build();
    const result = applyCodeSigningConfig(resources, options);

    expect(result.userFunctions).toBe(2);
    expect(result.customResourceFunctions).toBe(1);
    expect(result.imageFunctions).toEqual(['svc-imageFunction']);
    expect(result.unsignableFunctions).toEqual(['svc-some-other-plugin-warmer']);
  });

  it('accounts for every function in the template exactly once', () => {
    const resources = build();
    const result = applyCodeSigningConfig(resources, options);

    const total = Object.values(resources).filter(
      (resource) => resource.Type === 'AWS::Lambda::Function'
    ).length;

    expect(
      result.userFunctions +
        result.customResourceFunctions +
        result.skippedCustomResourceFunctions.length +
        result.imageFunctions.length +
        result.unsignableFunctions.length
    ).toBe(total);
  });

  it('falls back to the logical ID when FunctionName is not a plain string', () => {
    const result = applyCodeSigningConfig(
      {
        MysteryLambda: {
          Type: 'AWS::Lambda::Function',
          Properties: {
            FunctionName: { Ref: 'SomeParameter' },
            Code: { S3Bucket: 'deploy', S3Key: 'serverless/svc/dev/1/mystery.zip' },
          },
        },
      },
      options
    );

    expect(result.unsignableFunctions).toEqual(['MysteryLambda']);
  });
});
